version: '3.8'

services:
  pokedex:
    container_name: graphql_pokemon
    image: ghcr.io/favware/graphql-pokemon:latest
    restart: always
    networks:
      - infi
    ports:
      - '4000:4000'

  redis:
    command: 'redis-server --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    networks:
      - infi
    ports:
      - '1424:6379'
    restart: always
    logging:
      options:
        max-size: '20m'
        max-file: '3'

  influx:
    command: 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt'
    container_name: influxdb
    image: 'influxdb:2.1-alpine'
    networks:
      - infi
    ports:
      - '1425:8086'
    restart: always
    volumes:
      - 'influx-data:/var/lib/influxdb2'
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  dragonite:
    build:
      context: ../
    container_name: dragonite
    depends_on:
      - redis
      - influx
    env_file:
      - ../src/.env.development
      - ../src/.env.development.local
    image: dragonite:latest
    logging:
      options:
        max-size: '1g'
        max-file: '3'
    networks:
      - infi
    restart: always
    tty: true

volumes:
  influx-data:
    external: true

networks:
  infi:
